import { create } from 'zustand';

interface Message {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: Date;
}

interface AgentStatus {
  name: string;
  status: 'pending' | 'running' | 'completed' | 'error';
  duration?: number;
}

interface Suggestion {
  id: string;
  type: 'improvement' | 'warning' | 'optimization' | 'security' | 'cost';
  title: string;
  description: string;
}

interface AIState {
  messages: Message[];
  isGenerating: boolean;
  pipelineStatus: AgentStatus[];
  suggestions: Suggestion[];
  generatedDSL: string;

  addMessage: (message: Message) => void;
  setMessages: (messages: Message[]) => void;
  setIsGenerating: (generating: boolean) => void;
  setPipelineStatus: (status: AgentStatus[]) => void;
  updateAgentStatus: (agent: string, status: AgentStatus['status']) => void;
  setSuggestions: (suggestions: Suggestion[]) => void;
  clearChat: () => void;
  runPipeline: () => void;
  setGeneratedDSL: (dsl: string) => void;
}

const AGENTS = ['Planner', 'Requirements', 'Architect', 'Database', 'API', 'Infrastructure'];
const DSL_STORAGE_KEY = 'orbit-ai-generated-dsl';

const GENERATED_DSL = `# AI-Generated Architecture
# Generated by Orbit Studio AI Architect

Frontend [icon: frontend]
API Gateway [icon: gateway, status: active]
Auth Service [icon: auth]
Backend API [icon: backend, status: active]
PostgreSQL [icon: database, status: active]
Redis Cache [icon: cache]
Worker Queue [icon: queue]
CDN [icon: cdn]

Frontend -> CDN: Static Assets
CDN -> API Gateway: API Requests
API Gateway -> Auth Service: Authenticate
API Gateway -> Backend API: Route Requests
Backend API -> PostgreSQL: Persist Data
Backend API -> Redis Cache: Cache Queries
Backend API -> Worker Queue: Background Jobs

Group "AWS Cloud" {
  API Gateway
  Auth Service
  Backend API
  PostgreSQL
  Redis Cache
  Worker Queue
}
`;

function delay(ms: number) { return new Promise((r) => setTimeout(r, ms)); }

export const useAIStore = create<AIState>((set, get) => ({
  messages: [],
  isGenerating: false,
  pipelineStatus: [],
  suggestions: [],
  generatedDSL: '',

  addMessage: (message) => set((state) => ({ messages: [...state.messages, message] })),
  setMessages: (messages) => set({ messages }),
  setIsGenerating: (generating) => set({ isGenerating: generating }),
  setPipelineStatus: (status) => set({ pipelineStatus: status }),
  updateAgentStatus: (agent, status) =>
    set((state) => ({
      pipelineStatus: state.pipelineStatus.map((a) =>
        a.name === agent ? { ...a, status } : a,
      ),
    })),
  setSuggestions: (suggestions) => set({ suggestions }),
  clearChat: () => set({ messages: [], pipelineStatus: [], suggestions: [], generatedDSL: '' }),
  setGeneratedDSL: (dsl) => set({ generatedDSL: dsl }),

  runPipeline: async () => {
    const { isGenerating } = get();
    if (isGenerating) return;

    set({ isGenerating: true, suggestions: [], generatedDSL: '' });
    const pipeline = AGENTS.map((name) => ({ name, status: 'pending' as const }));
    set({ pipelineStatus: pipeline });

    for (const agentName of AGENTS) {
      get().updateAgentStatus(agentName, 'running');
      await delay(600 + Math.random() * 500);

      if (agentName === 'Planner') {
        get().addMessage({
          id: `sys_${Date.now()}`,
          role: 'system',
          content: 'Planning 3-tier architecture with React frontend, Node.js API, PostgreSQL, Redis cache, and Docker deployment.',
          timestamp: new Date(),
        });
      }
      if (agentName === 'Architect') {
        get().addMessage({
          id: `sys_${Date.now()}`,
          role: 'assistant',
          content: 'Generated architecture with 8 components. DSL code is ready — switch to <strong>DaC mode</strong> to edit.',
          timestamp: new Date(),
        });
      }

      get().updateAgentStatus(agentName, 'completed');
    }

    localStorage.setItem(DSL_STORAGE_KEY, GENERATED_DSL);
    set({
      generatedDSL: GENERATED_DSL,
      suggestions: [
        { id: 's1', type: 'optimization', title: 'Add CDN layer', description: 'Reduce static asset latency by 60% for global users.' },
        { id: 's2', type: 'security', title: 'Enable WAF', description: 'Protect against common attack vectors with a Web Application Firewall.' },
        { id: 's3', type: 'cost', title: 'Right-size instances', description: 'Estimated monthly cost: $1,200. Consider reserved instances for 40% savings.' },
      ],
      isGenerating: false,
    });
  },
}));
