import type { Node, Edge } from '@xyflow/react';

export interface TemplateData {
  id: string;
  name: string;
  description: string;
  nodes: Node[];
  edges: Edge[];
}

export const TEMPLATES_DATA: Record<string, TemplateData> = {
  'netflix-clone': {
    id: 'netflix-clone',
    name: 'Netflix Clone',
    description: 'Video streaming platform with microservices',
    nodes: [
      { id: 'cdn', type: 'archNode', position: { x: 80, y: 20 }, data: { label: 'CloudFront CDN', type: 'cdn', metadata: { status: 'active', provider: 'AWS' } } },
      { id: 'gateway', type: 'archNode', position: { x: 80, y: 140 }, data: { label: 'API Gateway', type: 'gateway', metadata: { status: 'active', provider: 'AWS' } } },
      { id: 'auth', type: 'archNode', position: { x: -160, y: 260 }, data: { label: 'Auth Service', type: 'auth', metadata: { status: 'active', provider: 'AWS' } } },
      { id: 'frontend', type: 'archNode', position: { x: -40, y: 260 }, data: { label: 'Web Frontend', type: 'frontend', metadata: { status: 'active', provider: 'React' } } },
      { id: 'backend-catalog', type: 'archNode', position: { x: 80, y: 260 }, data: { label: 'Catalog Service', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'backend-stream', type: 'archNode', position: { x: 200, y: 260 }, data: { label: 'Streaming Service', type: 'microservice', metadata: { status: 'active', provider: 'Go' } } },
      { id: 'backend-reco', type: 'archNode', position: { x: 320, y: 260 }, data: { label: 'Recommendation Engine', type: 'ai-model', metadata: { status: 'active', provider: 'Python/ML' } } },
      { id: 'queue-encode', type: 'archNode', position: { x: 80, y: 380 }, data: { label: 'Encoding Queue', type: 'queue', metadata: { status: 'active', provider: 'SQS' } } },
      { id: 'worker-encode', type: 'archNode', position: { x: 200, y: 380 }, data: { label: 'Encoding Worker', type: 'worker', metadata: { status: 'active', provider: 'Lambda' } } },
      { id: 'cache', type: 'archNode', position: { x: -160, y: 380 }, data: { label: 'Redis Cache', type: 'cache', metadata: { status: 'active', provider: 'ElastiCache' } } },
      { id: 'db-primary', type: 'archNode', position: { x: 80, y: 500 }, data: { label: 'PostgreSQL Primary', type: 'database', metadata: { status: 'active', provider: 'RDS' } } },
      { id: 'db-replica', type: 'archNode', position: { x: 200, y: 500 }, data: { label: 'PostgreSQL Replica', type: 'database', metadata: { status: 'active', provider: 'RDS' } } },
      { id: 'storage', type: 'archNode', position: { x: 320, y: 380 }, data: { label: 'S3 Media Storage', type: 'storage', metadata: { status: 'active', provider: 'AWS S3' } } },
      { id: 'monitoring', type: 'archNode', position: { x: 200, y: 20 }, data: { label: 'CloudWatch', type: 'monitoring', metadata: { status: 'active', provider: 'AWS' } } },
    ],
    edges: [
      { id: 'e-cdn-gw', source: 'cdn', target: 'gateway', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'e-cdn-mo', source: 'cdn', target: 'monitoring', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'e-gw-auth', source: 'gateway', target: 'auth', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'e-gw-fe', source: 'gateway', target: 'frontend', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'e-gw-cat', source: 'gateway', target: 'backend-catalog', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'e-gw-str', source: 'gateway', target: 'backend-stream', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'e-gw-rec', source: 'gateway', target: 'backend-reco', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'e-cat-db', source: 'backend-catalog', target: 'db-primary', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'e-str-que', source: 'backend-stream', target: 'queue-encode', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'e-que-wrk', source: 'queue-encode', target: 'worker-encode', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'e-wrk-str', source: 'worker-encode', target: 'storage', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'e-str-strm', source: 'storage', target: 'backend-stream', sourceHandle: 'top', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'e-fe-cache', source: 'frontend', target: 'cache', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'e-db-rep', source: 'db-primary', target: 'db-replica', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5, strokeDasharray: '4 4' } },
    ],
  },

  'saas-platform': {
    id: 'saas-platform',
    name: 'SaaS Platform',
    description: 'Multi-tenant SaaS app with billing',
    nodes: [
      { id: 'gw', type: 'archNode', position: { x: 140, y: 20 }, data: { label: 'API Gateway', type: 'gateway', metadata: { status: 'active', provider: 'AWS' } } },
      { id: 'fe', type: 'archNode', position: { x: 20, y: 140 }, data: { label: 'Web App', type: 'frontend', metadata: { status: 'active', provider: 'Next.js' } } },
      { id: 'be-api', type: 'archNode', position: { x: 140, y: 140 }, data: { label: 'API Service', type: 'backend', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'be-billing', type: 'archNode', position: { x: 260, y: 140 }, data: { label: 'Billing Service', type: 'microservice', metadata: { status: 'active', provider: 'Go' } } },
      { id: 'be-tenant', type: 'archNode', position: { x: 140, y: 260 }, data: { label: 'Tenant Manager', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'cache', type: 'archNode', position: { x: -60, y: 260 }, data: { label: 'Redis Cache', type: 'cache', metadata: { status: 'active', provider: 'ElastiCache' } } },
      { id: 'queue', type: 'archNode', position: { x: 260, y: 260 }, data: { label: 'Task Queue', type: 'queue', metadata: { status: 'active', provider: 'SQS' } } },
      { id: 'worker', type: 'archNode', position: { x: 260, y: 380 }, data: { label: 'Background Worker', type: 'worker', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'db-main', type: 'archNode', position: { x: 140, y: 380 }, data: { label: 'PostgreSQL', type: 'database', metadata: { status: 'active', provider: 'RDS' } } },
      { id: 'db-analytics', type: 'archNode', position: { x: 20, y: 380 }, data: { label: 'Analytics DB', type: 'database', metadata: { status: 'active', provider: 'Redshift' } } },
      { id: 'storage', type: 'archNode', position: { x: 380, y: 380 }, data: { label: 'File Storage', type: 'storage', metadata: { status: 'active', provider: 'S3' } } },
      { id: 'mon', type: 'archNode', position: { x: 20, y: 20 }, data: { label: 'Monitoring', type: 'monitoring', metadata: { status: 'active', provider: 'Datadog' } } },
    ],
    edges: [
      { id: 's-gw-fe', source: 'gw', target: 'fe', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 's-gw-api', source: 'gw', target: 'be-api', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 's-gw-bill', source: 'gw', target: 'be-billing', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 's-api-tenant', source: 'be-api', target: 'be-tenant', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 's-api-cache', source: 'be-api', target: 'cache', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 's-bill-queue', source: 'be-billing', target: 'queue', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 's-queue-wrk', source: 'queue', target: 'worker', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 's-tenant-db', source: 'be-tenant', target: 'db-main', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 's-api-db', source: 'be-api', target: 'db-main', sourceHandle: 'right', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 's-api-analytics', source: 'be-api', target: 'db-analytics', sourceHandle: 'left', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 's-wrk-storage', source: 'worker', target: 'storage', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 's-gw-mon', source: 'gw', target: 'mon', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
    ],
  },

  'e-commerce': {
    id: 'e-commerce',
    name: 'E-Commerce',
    description: 'Full e-commerce with cart, orders, payments',
    nodes: [
      { id: 'gw', type: 'archNode', position: { x: 140, y: 20 }, data: { label: 'API Gateway', type: 'gateway', metadata: { status: 'active', provider: 'AWS' } } },
      { id: 'fe', type: 'archNode', position: { x: 20, y: 140 }, data: { label: 'Store Frontend', type: 'frontend', metadata: { status: 'active', provider: 'Next.js' } } },
      { id: 'be-prod', type: 'archNode', position: { x: 140, y: 140 }, data: { label: 'Product Service', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'be-cart', type: 'archNode', position: { x: 260, y: 140 }, data: { label: 'Cart Service', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'be-order', type: 'archNode', position: { x: 140, y: 260 }, data: { label: 'Order Service', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'be-pay', type: 'archNode', position: { x: 260, y: 260 }, data: { label: 'Payment Service', type: 'microservice', metadata: { status: 'active', provider: 'Stripe' } } },
      { id: 'be-inv', type: 'archNode', position: { x: 20, y: 260 }, data: { label: 'Inventory Service', type: 'microservice', metadata: { status: 'active', provider: 'Go' } } },
      { id: 'cache', type: 'archNode', position: { x: 380, y: 140 }, data: { label: 'Redis Cache', type: 'cache', metadata: { status: 'active', provider: 'ElastiCache' } } },
      { id: 'queue', type: 'archNode', position: { x: 380, y: 260 }, data: { label: 'Order Queue', type: 'queue', metadata: { status: 'active', provider: 'SQS' } } },
      { id: 'db-prod', type: 'archNode', position: { x: 140, y: 380 }, data: { label: 'Product DB', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL' } } },
      { id: 'db-order', type: 'archNode', position: { x: 260, y: 380 }, data: { label: 'Order DB', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL' } } },
      { id: 'search', type: 'archNode', position: { x: 20, y: 380 }, data: { label: 'Search Index', type: 'database', metadata: { status: 'active', provider: 'Elasticsearch' } } },
    ],
    edges: [
      { id: 'ec-gw-fe', source: 'gw', target: 'fe', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'ec-gw-prod', source: 'gw', target: 'be-prod', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'ec-gw-cart', source: 'gw', target: 'be-cart', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'ec-gw-ord', source: 'gw', target: 'be-order', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'ec-gw-pay', source: 'gw', target: 'be-pay', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'ec-gw-inv', source: 'gw', target: 'be-inv', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'ec-prod-cache', source: 'be-prod', target: 'cache', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'ec-cart-cache', source: 'be-cart', target: 'cache', sourceHandle: 'right', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'ec-ord-queue', source: 'be-order', target: 'queue', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'ec-prod-db', source: 'be-prod', target: 'db-prod', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'ec-ord-db', source: 'be-order', target: 'db-order', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'ec-inv-db', source: 'be-inv', target: 'db-prod', sourceHandle: 'bottom', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'ec-pay-ord', source: 'be-pay', target: 'be-order', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'ec-prod-search', source: 'be-prod', target: 'search', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
    ],
  },

  'healthcare': {
    id: 'healthcare',
    name: 'Healthcare Platform',
    description: 'HIPAA-compliant healthcare system',
    nodes: [
      { id: 'gw', type: 'archNode', position: { x: 140, y: 20 }, data: { label: 'API Gateway', type: 'gateway', metadata: { status: 'active', provider: 'AWS' } } },
      { id: 'fe-patient', type: 'archNode', position: { x: 20, y: 140 }, data: { label: 'Patient Portal', type: 'frontend', metadata: { status: 'active', provider: 'React' } } },
      { id: 'fe-doctor', type: 'archNode', position: { x: 140, y: 140 }, data: { label: 'Doctor Dashboard', type: 'frontend', metadata: { status: 'active', provider: 'React' } } },
      { id: 'be-pat', type: 'archNode', position: { x: 20, y: 260 }, data: { label: 'Patient Service', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'be-appt', type: 'archNode', position: { x: 140, y: 260 }, data: { label: 'Appointment Service', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'be-ehr', type: 'archNode', position: { x: 260, y: 260 }, data: { label: 'EHR Service', type: 'microservice', metadata: { status: 'active', provider: 'HIPAA' } } },
      { id: 'be-billing', type: 'archNode', position: { x: 260, y: 140 }, data: { label: 'Medical Billing', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'auth', type: 'archNode', position: { x: -100, y: 140 }, data: { label: 'HIPAA Auth', type: 'auth', metadata: { status: 'active', provider: 'Cognito' } } },
      { id: 'db-pat', type: 'archNode', position: { x: 20, y: 380 }, data: { label: 'Patient DB', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL' } } },
      { id: 'db-ehr', type: 'archNode', position: { x: 260, y: 380 }, data: { label: 'EHR Database', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL Encrypted' } } },
      { id: 'db-appt', type: 'archNode', position: { x: 140, y: 380 }, data: { label: 'Appointment DB', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL' } } },
      { id: 'audit', type: 'archNode', position: { x: 380, y: 380 }, data: { label: 'Audit Log', type: 'database', metadata: { status: 'active', provider: 'S3 + Athena' } } },
      { id: 'cache', type: 'archNode', position: { x: -100, y: 260 }, data: { label: 'Redis Cache', type: 'cache', metadata: { status: 'active', provider: 'ElastiCache' } } },
    ],
    edges: [
      { id: 'h-gw-pt', source: 'gw', target: 'fe-patient', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'h-gw-dr', source: 'gw', target: 'fe-doctor', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'h-gw-auth', source: 'gw', target: 'auth', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'h-gw-bill', source: 'gw', target: 'be-billing', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'h-pt-pat', source: 'fe-patient', target: 'be-pat', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'h-dr-ehr', source: 'fe-doctor', target: 'be-ehr', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'h-pat-db', source: 'be-pat', target: 'db-pat', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'h-appt-db', source: 'be-appt', target: 'db-appt', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'h-ehr-db', source: 'be-ehr', target: 'db-ehr', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'h-ehr-audit', source: 'be-ehr', target: 'audit', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'h-pat-cache', source: 'be-pat', target: 'cache', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'h-appt-pat', source: 'be-appt', target: 'be-pat', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'h-ehr-bill', source: 'be-ehr', target: 'be-billing', sourceHandle: 'top', targetHandle: 'bottom', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
    ],
  },

  'banking-api': {
    id: 'banking-api',
    name: 'Banking API',
    description: 'Fintech API with transaction processing',
    nodes: [
      { id: 'gw', type: 'archNode', position: { x: 140, y: 20 }, data: { label: 'API Gateway', type: 'gateway', metadata: { status: 'active', provider: 'Kong' } } },
      { id: 'fe', type: 'archNode', position: { x: 20, y: 140 }, data: { label: 'Bank Dashboard', type: 'frontend', metadata: { status: 'active', provider: 'Next.js' } } },
      { id: 'be-acc', type: 'archNode', position: { x: 140, y: 140 }, data: { label: 'Account Service', type: 'microservice', metadata: { status: 'active', provider: 'Java' } } },
      { id: 'be-txn', type: 'archNode', position: { x: 260, y: 140 }, data: { label: 'Transaction Service', type: 'microservice', metadata: { status: 'active', provider: 'Java' } } },
      { id: 'be-fraud', type: 'archNode', position: { x: 140, y: 260 }, data: { label: 'Fraud Detection', type: 'ai-model', metadata: { status: 'active', provider: 'Python/ML' } } },
      { id: 'be-notif', type: 'archNode', position: { x: 260, y: 260 }, data: { label: 'Notification Service', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'auth', type: 'archNode', position: { x: -60, y: 140 }, data: { label: 'OAuth2 Server', type: 'auth', metadata: { status: 'active', provider: 'Auth0' } } },
      { id: 'db-acc', type: 'archNode', position: { x: 140, y: 380 }, data: { label: 'Account DB', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL' } } },
      { id: 'db-txn', type: 'archNode', position: { x: 260, y: 380 }, data: { label: 'Transaction DB', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL' } } },
      { id: 'queue', type: 'archNode', position: { x: 380, y: 260 }, data: { label: 'Txn Queue', type: 'queue', metadata: { status: 'active', provider: 'Kafka' } } },
      { id: 'cache', type: 'archNode', position: { x: -60, y: 260 }, data: { label: 'Redis Cache', type: 'cache', metadata: { status: 'active', provider: 'ElastiCache' } } },
      { id: 'mon', type: 'archNode', position: { x: 380, y: 20 }, data: { label: 'Compliance Monitor', type: 'monitoring', metadata: { status: 'active', provider: 'Splunk' } } },
    ],
    edges: [
      { id: 'b-gw-fe', source: 'gw', target: 'fe', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'b-gw-acc', source: 'gw', target: 'be-acc', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'b-gw-txn', source: 'gw', target: 'be-txn', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'b-gw-auth', source: 'gw', target: 'auth', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'b-acc-db', source: 'be-acc', target: 'db-acc', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'b-txn-db', source: 'be-txn', target: 'db-txn', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'b-txn-queue', source: 'be-txn', target: 'queue', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'b-txn-fraud', source: 'be-txn', target: 'be-fraud', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'b-fraud-notif', source: 'be-fraud', target: 'be-notif', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'b-acc-cache', source: 'be-acc', target: 'cache', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'b-gw-mon', source: 'gw', target: 'mon', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
    ],
  },

  'ai-chatbot': {
    id: 'ai-chatbot',
    name: 'AI Chatbot Platform',
    description: 'LLM-powered chatbot architecture',
    nodes: [
      { id: 'gw', type: 'archNode', position: { x: 140, y: 20 }, data: { label: 'API Gateway', type: 'gateway', metadata: { status: 'active', provider: 'AWS' } } },
      { id: 'fe', type: 'archNode', position: { x: 20, y: 140 }, data: { label: 'Chat UI', type: 'frontend', metadata: { status: 'active', provider: 'Next.js' } } },
      { id: 'be-chat', type: 'archNode', position: { x: 140, y: 140 }, data: { label: 'Chat Service', type: 'backend', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'ai-llm', type: 'archNode', position: { x: 260, y: 140 }, data: { label: 'LLM Gateway', type: 'ai-model', metadata: { status: 'active', provider: 'OpenAI' } } },
      { id: 'ai-embed', type: 'archNode', position: { x: 260, y: 260 }, data: { label: 'Embedding Service', type: 'ai-model', metadata: { status: 'active', provider: 'OpenAI' } } },
      { id: 'be-context', type: 'archNode', position: { x: 140, y: 260 }, data: { label: 'Context Manager', type: 'microservice', metadata: { status: 'active', provider: 'Python' } } },
      { id: 'db-vector', type: 'archNode', position: { x: 380, y: 260 }, data: { label: 'Vector Database', type: 'database', metadata: { status: 'active', provider: 'Pinecone' } } },
      { id: 'db-chat', type: 'archNode', position: { x: 140, y: 380 }, data: { label: 'Chat History DB', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL' } } },
      { id: 'cache', type: 'archNode', position: { x: -60, y: 260 }, data: { label: 'Redis Cache', type: 'cache', metadata: { status: 'active', provider: 'ElastiCache' } } },
      { id: 'auth', type: 'archNode', position: { x: -60, y: 140 }, data: { label: 'Auth Service', type: 'auth', metadata: { status: 'active', provider: 'Clerk' } } },
      { id: 'queue', type: 'archNode', position: { x: 260, y: 380 }, data: { label: 'Analytics Queue', type: 'queue', metadata: { status: 'active', provider: 'SQS' } } },
      { id: 'mon', type: 'archNode', position: { x: 20, y: 20 }, data: { label: 'LangSmith Trace', type: 'monitoring', metadata: { status: 'active', provider: 'LangChain' } } },
    ],
    edges: [
      { id: 'a-gw-fe', source: 'gw', target: 'fe', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'a-gw-chat', source: 'gw', target: 'be-chat', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'a-gw-auth', source: 'gw', target: 'auth', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'a-chat-llm', source: 'be-chat', target: 'ai-llm', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'a-chat-ctx', source: 'be-chat', target: 'be-context', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'a-ctx-embed', source: 'be-context', target: 'ai-embed', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'a-embed-vec', source: 'ai-embed', target: 'db-vector', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'a-ctx-db', source: 'be-context', target: 'db-chat', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'a-chat-db', source: 'be-chat', target: 'db-chat', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'a-chat-cache', source: 'be-chat', target: 'cache', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'a-chat-queue', source: 'be-chat', target: 'queue', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
      { id: 'a-gw-mon', source: 'gw', target: 'mon', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#475569', strokeWidth: 1.5 } },
    ],
  },
};
