import type { Node, Edge } from '@xyflow/react';

export interface TemplateData {
  id: string;
  name: string;
  description: string;
  nodes: Node[];
  edges: Edge[];
}

export const TEMPLATES_DATA: Record<string, TemplateData> = {
  'netflix-clone': {
    id: 'netflix-clone',
    name: 'Netflix Clone',
    description: 'Video streaming platform with microservices',
    nodes: [
      { id: 'cdn', type: 'archNode', position: { x: 80, y: 20 }, data: { label: 'CloudFront CDN', type: 'cdn', metadata: { status: 'active', provider: 'AWS' } } },
      { id: 'gateway', type: 'archNode', position: { x: 80, y: 140 }, data: { label: 'API Gateway', type: 'gateway', metadata: { status: 'active', provider: 'AWS' } } },
      { id: 'auth', type: 'archNode', position: { x: -160, y: 260 }, data: { label: 'Auth Service', type: 'auth', metadata: { status: 'active', provider: 'AWS' } } },
      { id: 'frontend', type: 'archNode', position: { x: -40, y: 260 }, data: { label: 'Web Frontend', type: 'frontend', metadata: { status: 'active', provider: 'React' } } },
      { id: 'catalog', type: 'archNode', position: { x: 80, y: 260 }, data: { label: 'Catalog Service', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'streaming', type: 'archNode', position: { x: 200, y: 260 }, data: { label: 'Streaming Service', type: 'microservice', metadata: { status: 'active', provider: 'Go' } } },
      { id: 'reco', type: 'archNode', position: { x: 320, y: 260 }, data: { label: 'Recommendation Engine', type: 'ai-model', metadata: { status: 'active', provider: 'Python/ML' } } },
      { id: 'queue', type: 'archNode', position: { x: 80, y: 380 }, data: { label: 'Encoding Queue', type: 'queue', metadata: { status: 'active', provider: 'SQS' } } },
      { id: 'worker', type: 'archNode', position: { x: 200, y: 380 }, data: { label: 'Encoding Worker', type: 'worker', metadata: { status: 'active', provider: 'Lambda' } } },
      { id: 'cache', type: 'archNode', position: { x: -160, y: 380 }, data: { label: 'Redis Cache', type: 'cache', metadata: { status: 'active', provider: 'ElastiCache' } } },
      { id: 'db', type: 'archNode', position: { x: 80, y: 500 }, data: { label: 'PostgreSQL', type: 'database', metadata: { status: 'active', provider: 'RDS' } } },
      { id: 'storage', type: 'archNode', position: { x: 320, y: 380 }, data: { label: 'S3 Media Storage', type: 'storage', metadata: { status: 'active', provider: 'AWS S3' } } },
      { id: 'monitoring', type: 'archNode', position: { x: 200, y: 20 }, data: { label: 'CloudWatch', type: 'monitoring', metadata: { status: 'active', provider: 'AWS' } } },
    ],
    edges: [
      { id: 'e1', source: 'cdn', target: 'gateway', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'e2', source: 'cdn', target: 'monitoring', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'e3', source: 'gateway', target: 'auth', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'e4', source: 'gateway', target: 'frontend', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'e5', source: 'gateway', target: 'catalog', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'e6', source: 'gateway', target: 'streaming', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'e7', source: 'gateway', target: 'reco', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'e8', source: 'catalog', target: 'db', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'e9', source: 'streaming', target: 'queue', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'e10', source: 'queue', target: 'worker', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'e11', source: 'worker', target: 'storage', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'e12', source: 'storage', target: 'streaming', sourceHandle: 'top', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'e13', source: 'frontend', target: 'cache', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
    ],
  },

  'saas-platform': {
    id: 'saas-platform',
    name: 'SaaS Platform',
    description: 'Multi-tenant SaaS app with billing',
    nodes: [
      { id: 'gw', type: 'archNode', position: { x: 140, y: 20 }, data: { label: 'API Gateway', type: 'gateway', metadata: { status: 'active', provider: 'AWS' } } },
      { id: 'fe', type: 'archNode', position: { x: 20, y: 140 }, data: { label: 'Web App', type: 'frontend', metadata: { status: 'active', provider: 'Next.js' } } },
      { id: 'api', type: 'archNode', position: { x: 140, y: 140 }, data: { label: 'API Service', type: 'backend', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'billing', type: 'archNode', position: { x: 260, y: 140 }, data: { label: 'Billing Service', type: 'microservice', metadata: { status: 'active', provider: 'Go' } } },
      { id: 'tenant', type: 'archNode', position: { x: 140, y: 260 }, data: { label: 'Tenant Manager', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'cache', type: 'archNode', position: { x: -60, y: 260 }, data: { label: 'Redis Cache', type: 'cache', metadata: { status: 'active', provider: 'ElastiCache' } } },
      { id: 'queue', type: 'archNode', position: { x: 260, y: 260 }, data: { label: 'Task Queue', type: 'queue', metadata: { status: 'active', provider: 'SQS' } } },
      { id: 'worker', type: 'archNode', position: { x: 260, y: 380 }, data: { label: 'Background Worker', type: 'worker', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'db', type: 'archNode', position: { x: 140, y: 380 }, data: { label: 'PostgreSQL', type: 'database', metadata: { status: 'active', provider: 'RDS' } } },
      { id: 'analytics', type: 'archNode', position: { x: 20, y: 380 }, data: { label: 'Analytics DB', type: 'database', metadata: { status: 'active', provider: 'Redshift' } } },
      { id: 'storage', type: 'archNode', position: { x: 380, y: 380 }, data: { label: 'File Storage', type: 'storage', metadata: { status: 'active', provider: 'S3' } } },
      { id: 'mon', type: 'archNode', position: { x: 20, y: 20 }, data: { label: 'Monitoring', type: 'monitoring', metadata: { status: 'active', provider: 'Datadog' } } },
    ],
    edges: [
      { id: 's1', source: 'gw', target: 'fe', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 's2', source: 'gw', target: 'api', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 's3', source: 'gw', target: 'billing', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 's4', source: 'api', target: 'tenant', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 's5', source: 'api', target: 'cache', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 's6', source: 'billing', target: 'queue', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 's7', source: 'queue', target: 'worker', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 's8', source: 'tenant', target: 'db', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 's9', source: 'api', target: 'db', sourceHandle: 'right', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 's10', source: 'api', target: 'analytics', sourceHandle: 'left', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 's11', source: 'worker', target: 'storage', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 's12', source: 'gw', target: 'mon', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
    ],
  },

  'e-commerce': {
    id: 'e-commerce',
    name: 'E-Commerce Platform',
    description: 'Full e-commerce with cart, orders, payments',
    nodes: [
      { id: 'gw', type: 'archNode', position: { x: 140, y: 20 }, data: { label: 'API Gateway', type: 'gateway', metadata: { status: 'active', provider: 'AWS' } } },
      { id: 'fe', type: 'archNode', position: { x: 20, y: 140 }, data: { label: 'Store Frontend', type: 'frontend', metadata: { status: 'active', provider: 'Next.js' } } },
      { id: 'prod', type: 'archNode', position: { x: 140, y: 140 }, data: { label: 'Product Service', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'cart', type: 'archNode', position: { x: 260, y: 140 }, data: { label: 'Cart Service', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'order', type: 'archNode', position: { x: 140, y: 260 }, data: { label: 'Order Service', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'pay', type: 'archNode', position: { x: 260, y: 260 }, data: { label: 'Payment Service', type: 'microservice', metadata: { status: 'active', provider: 'Stripe' } } },
      { id: 'inv', type: 'archNode', position: { x: 20, y: 260 }, data: { label: 'Inventory Service', type: 'microservice', metadata: { status: 'active', provider: 'Go' } } },
      { id: 'cache', type: 'archNode', position: { x: 380, y: 140 }, data: { label: 'Redis Cache', type: 'cache', metadata: { status: 'active', provider: 'ElastiCache' } } },
      { id: 'queue', type: 'archNode', position: { x: 380, y: 260 }, data: { label: 'Order Queue', type: 'queue', metadata: { status: 'active', provider: 'SQS' } } },
      { id: 'db-prod', type: 'archNode', position: { x: 140, y: 380 }, data: { label: 'Product DB', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL' } } },
      { id: 'db-order', type: 'archNode', position: { x: 260, y: 380 }, data: { label: 'Order DB', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL' } } },
      { id: 'search', type: 'archNode', position: { x: 20, y: 380 }, data: { label: 'Search Index', type: 'database', metadata: { status: 'active', provider: 'Elasticsearch' } } },
    ],
    edges: [
      { id: 'c1', source: 'gw', target: 'fe', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'c2', source: 'gw', target: 'prod', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'c3', source: 'gw', target: 'cart', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'c4', source: 'gw', target: 'order', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'c5', source: 'gw', target: 'pay', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'c6', source: 'gw', target: 'inv', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'c7', source: 'prod', target: 'cache', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'c8', source: 'prod', target: 'db-prod', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'c9', source: 'order', target: 'db-order', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'c10', source: 'order', target: 'queue', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'c11', source: 'pay', target: 'order', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'c12', source: 'prod', target: 'search', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
    ],
  },

  'healthcare': {
    id: 'healthcare',
    name: 'Healthcare Platform',
    description: 'HIPAA-compliant healthcare system',
    nodes: [
      { id: 'gw', type: 'archNode', position: { x: 140, y: 20 }, data: { label: 'API Gateway', type: 'gateway', metadata: { status: 'active', provider: 'AWS' } } },
      { id: 'patient-portal', type: 'archNode', position: { x: 20, y: 140 }, data: { label: 'Patient Portal', type: 'frontend', metadata: { status: 'active', provider: 'React' } } },
      { id: 'doctor-dash', type: 'archNode', position: { x: 140, y: 140 }, data: { label: 'Doctor Dashboard', type: 'frontend', metadata: { status: 'active', provider: 'React' } } },
      { id: 'patient-svc', type: 'archNode', position: { x: 20, y: 260 }, data: { label: 'Patient Service', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'appt-svc', type: 'archNode', position: { x: 140, y: 260 }, data: { label: 'Appointment Service', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'ehr-svc', type: 'archNode', position: { x: 260, y: 260 }, data: { label: 'EHR Service', type: 'microservice', metadata: { status: 'active', provider: 'HIPAA' } } },
      { id: 'billing-svc', type: 'archNode', position: { x: 260, y: 140 }, data: { label: 'Medical Billing', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'auth', type: 'archNode', position: { x: -100, y: 140 }, data: { label: 'HIPAA Auth', type: 'auth', metadata: { status: 'active', provider: 'Cognito' } } },
      { id: 'db-patient', type: 'archNode', position: { x: 20, y: 380 }, data: { label: 'Patient DB', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL' } } },
      { id: 'db-ehr', type: 'archNode', position: { x: 260, y: 380 }, data: { label: 'EHR Database', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL Encrypted' } } },
      { id: 'db-appt', type: 'archNode', position: { x: 140, y: 380 }, data: { label: 'Appointment DB', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL' } } },
      { id: 'audit', type: 'archNode', position: { x: 380, y: 380 }, data: { label: 'Audit Log', type: 'database', metadata: { status: 'active', provider: 'S3 + Athena' } } },
      { id: 'cache', type: 'archNode', position: { x: -100, y: 260 }, data: { label: 'Redis Cache', type: 'cache', metadata: { status: 'active', provider: 'ElastiCache' } } },
    ],
    edges: [
      { id: 'h1', source: 'gw', target: 'patient-portal', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'h2', source: 'gw', target: 'doctor-dash', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'h3', source: 'gw', target: 'auth', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'h4', source: 'gw', target: 'billing-svc', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'h5', source: 'patient-portal', target: 'patient-svc', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'h6', source: 'doctor-dash', target: 'ehr-svc', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'h7', source: 'patient-svc', target: 'db-patient', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'h8', source: 'appt-svc', target: 'db-appt', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'h9', source: 'ehr-svc', target: 'db-ehr', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'h10', source: 'ehr-svc', target: 'audit', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'h11', source: 'patient-svc', target: 'cache', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'h12', source: 'appt-svc', target: 'patient-svc', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'h13', source: 'ehr-svc', target: 'billing-svc', sourceHandle: 'top', targetHandle: 'bottom', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
    ],
  },

  'banking-api': {
    id: 'banking-api',
    name: 'Banking API',
    description: 'Fintech API with transaction processing',
    nodes: [
      { id: 'gw', type: 'archNode', position: { x: 140, y: 20 }, data: { label: 'API Gateway', type: 'gateway', metadata: { status: 'active', provider: 'Kong' } } },
      { id: 'fe', type: 'archNode', position: { x: 20, y: 140 }, data: { label: 'Bank Dashboard', type: 'frontend', metadata: { status: 'active', provider: 'Next.js' } } },
      { id: 'acc', type: 'archNode', position: { x: 140, y: 140 }, data: { label: 'Account Service', type: 'microservice', metadata: { status: 'active', provider: 'Java' } } },
      { id: 'txn', type: 'archNode', position: { x: 260, y: 140 }, data: { label: 'Transaction Service', type: 'microservice', metadata: { status: 'active', provider: 'Java' } } },
      { id: 'fraud', type: 'archNode', position: { x: 140, y: 260 }, data: { label: 'Fraud Detection', type: 'ai-model', metadata: { status: 'active', provider: 'Python/ML' } } },
      { id: 'notif', type: 'archNode', position: { x: 260, y: 260 }, data: { label: 'Notification Service', type: 'microservice', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'auth', type: 'archNode', position: { x: -60, y: 140 }, data: { label: 'OAuth2 Server', type: 'auth', metadata: { status: 'active', provider: 'Auth0' } } },
      { id: 'db-acc', type: 'archNode', position: { x: 140, y: 380 }, data: { label: 'Account DB', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL' } } },
      { id: 'db-txn', type: 'archNode', position: { x: 260, y: 380 }, data: { label: 'Transaction DB', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL' } } },
      { id: 'queue', type: 'archNode', position: { x: 380, y: 260 }, data: { label: 'Txn Queue', type: 'queue', metadata: { status: 'active', provider: 'Kafka' } } },
      { id: 'cache', type: 'archNode', position: { x: -60, y: 260 }, data: { label: 'Redis Cache', type: 'cache', metadata: { status: 'active', provider: 'ElastiCache' } } },
      { id: 'mon', type: 'archNode', position: { x: 380, y: 20 }, data: { label: 'Compliance Monitor', type: 'monitoring', metadata: { status: 'active', provider: 'Splunk' } } },
    ],
    edges: [
      { id: 'b1', source: 'gw', target: 'fe', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'b2', source: 'gw', target: 'acc', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'b3', source: 'gw', target: 'txn', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'b4', source: 'gw', target: 'auth', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'b5', source: 'acc', target: 'db-acc', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'b6', source: 'txn', target: 'db-txn', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'b7', source: 'txn', target: 'queue', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'b8', source: 'txn', target: 'fraud', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'b9', source: 'fraud', target: 'notif', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'b10', source: 'acc', target: 'cache', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'b11', source: 'gw', target: 'mon', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
    ],
  },

  'ai-chatbot': {
    id: 'ai-chatbot',
    name: 'AI Chatbot Platform',
    description: 'LLM-powered chatbot architecture',
    nodes: [
      { id: 'gw', type: 'archNode', position: { x: 140, y: 20 }, data: { label: 'API Gateway', type: 'gateway', metadata: { status: 'active', provider: 'AWS' } } },
      { id: 'fe', type: 'archNode', position: { x: 20, y: 140 }, data: { label: 'Chat UI', type: 'frontend', metadata: { status: 'active', provider: 'Next.js' } } },
      { id: 'chat', type: 'archNode', position: { x: 140, y: 140 }, data: { label: 'Chat Service', type: 'backend', metadata: { status: 'active', provider: 'Node.js' } } },
      { id: 'llm', type: 'archNode', position: { x: 260, y: 140 }, data: { label: 'LLM Gateway', type: 'ai-model', metadata: { status: 'active', provider: 'OpenAI' } } },
      { id: 'embed', type: 'archNode', position: { x: 260, y: 260 }, data: { label: 'Embedding Service', type: 'ai-model', metadata: { status: 'active', provider: 'OpenAI' } } },
      { id: 'ctx', type: 'archNode', position: { x: 140, y: 260 }, data: { label: 'Context Manager', type: 'microservice', metadata: { status: 'active', provider: 'Python' } } },
      { id: 'vector', type: 'archNode', position: { x: 380, y: 260 }, data: { label: 'Vector Database', type: 'database', metadata: { status: 'active', provider: 'Pinecone' } } },
      { id: 'db-chat', type: 'archNode', position: { x: 140, y: 380 }, data: { label: 'Chat History DB', type: 'database', metadata: { status: 'active', provider: 'PostgreSQL' } } },
      { id: 'cache', type: 'archNode', position: { x: -60, y: 260 }, data: { label: 'Redis Cache', type: 'cache', metadata: { status: 'active', provider: 'ElastiCache' } } },
      { id: 'auth', type: 'archNode', position: { x: -60, y: 140 }, data: { label: 'Auth Service', type: 'auth', metadata: { status: 'active', provider: 'Clerk' } } },
      { id: 'queue', type: 'archNode', position: { x: 260, y: 380 }, data: { label: 'Analytics Queue', type: 'queue', metadata: { status: 'active', provider: 'SQS' } } },
      { id: 'mon', type: 'archNode', position: { x: 20, y: 20 }, data: { label: 'LangSmith Trace', type: 'monitoring', metadata: { status: 'active', provider: 'LangChain' } } },
    ],
    edges: [
      { id: 'a1', source: 'gw', target: 'fe', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'a2', source: 'gw', target: 'chat', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'a3', source: 'gw', target: 'auth', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'a4', source: 'chat', target: 'llm', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'a5', source: 'chat', target: 'ctx', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'a6', source: 'ctx', target: 'embed', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'a7', source: 'embed', target: 'vector', sourceHandle: 'right', targetHandle: 'left', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'a8', source: 'ctx', target: 'db-chat', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'a9', source: 'chat', target: 'db-chat', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'a10', source: 'chat', target: 'cache', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'a11', source: 'chat', target: 'queue', sourceHandle: 'bottom', targetHandle: 'top', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
      { id: 'a12', source: 'gw', target: 'mon', sourceHandle: 'left', targetHandle: 'right', type: 'smoothstep', style: { stroke: '#334155', strokeWidth: 1 } },
    ],
  },
};
